name = "leework"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Your Database Binding (Keep this!)
[[kv_namespaces]]
binding = "LEECH_DB"
id = "13fbf5261f684cb5b7f8b60df34826e2"
